### ISSUE TITLE
the trait `Clone` is not implemented for `AsymmetricSecretKey<_>`

### ISSUE THREAD

**Issue by Eh2406** [brycx/pasetors#79]
Why do keys not implement clone? There are other ways to write clone for this type in the public interface like `AsymmetricSecretKey::from(key.as_bytes()).expect("roundtrip")`. So this mostly seems like syntactic salt. Thoughts?

**Comment by brycx** [comment]
AFAIK, none of the keys currently implement `Clone`. The reason is simply that there has been no need for it so far and since the types hold secret data I've just held off on adding it. We should be able to easily add it, and as you point out yourself - there's already a way to do it non-idiomatically.

**Comment by brycx** [comment]
I have added this as part of #81, @Eh2406. It will be part of a `0.6.5` release today.

**Comment by Eh2406** [comment]
Thank you!
